app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['as'=>'site.', 'prefix'=>'/'], function(){
    route::get('',            ['as'=>'index', 'uses'=>'HomeController@index']);
    route::get('importar',    ['as' =>'upload', 'uses'=>'HomeController@upload']);
    route::post('importar',   ['uses'=>'HomeController@newFile']);
    route::get('editar/{id}', ['as'=>'edit', 'uses'=>'HomeController@edit']);
    route::put('editar/{id}', ['as'=>'edit', 'uses'=>'HomeController@update']);
    route::get('apagar/{id}', ['as'=>'delete', 'uses'=>'HomeController@delete']);
    route::delete('apagar/{id}', ['as'=>'delete', 'uses'=>'HomeController@deleteEl']);

});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable = ['name'];

    public function product()
    {
        return $this->hasMany('\App\Models\Product');
    }
}

app/Models/Log.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Log extends Model
{
    //
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'product_external_id', 
        'name', 
        'description', 
        'free_shipping', 
        'price', 
        'active',
        'category_id'
    ];

    public function category()
    {
        return $this->belongsTo('\App\Models\Category');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Jobs\ProcessXlsxJob;
use Repository\Controller as RepositoryController;

class HomeController extends Controller
{

    protected $repo;
    protected $message = '';
    protected $messageClass;

    public function __construct(RepositoryController $repo)
    {
        $this->repo = $repo;
    }

    public function index()
    {
        return view('home', ['products' => $this->repo->getProducts()]);
    }

    public function upload()
    {
        return view('upload', ['message'=>$this->message, 'messageClass'=>$this->messageClass]);
    }

    public function newFile(Request $request)
    {
        if($request->hasFile('file'))
        {
            $name = $request->file("file")->getClientOriginalName();
            $request->file('file')
                    ->move(
                        storage_path("xlsx"), 
                        $name
                    );
            $processar = new ProcessXlsxJob($name); 
            $this->dispatch($processar);
            $this->message = "Arquivo enviado com sucesso";
            $this->messageClass = "success";
            return $this->upload();
        }
        $this->messageClass = "warning";
        $this->message = "Favor escolher um arquivo";
        return $this->upload();
    }
    
    public function edit($id)
    {
        return view(
            'edit_product', 
            [
                'product' => $this->repo->getProduct($id),
                'message' => $this->message,
                'messageClass'   => $this->messageClass,
                'attrForm' => '',
                'sendButtonName' => "Atualizar",
                'url' => route('site.edit', $id),
                'method' => 'put',
                'title' => "Editar Produto"
            ]
        );
    }

    public function update(Request $request, $id)
    {
        $this->message = "Atualizado com sucesso";
        $this->messageClass="success";
        $data = $request->input();
        if(!$this->repo->change($data, $id))
        {
            $this->message = $this->repo->getError();
            $this->messageClass = "danger";
        }

        return $this->edit($id);
    }

    public function delete($id)
    {
        return view(
            'edit_product', 
            [
                'product' => $this->repo->getProduct($id),
                'message' => $this->message,
                'messageClass'   => $this->messageClass,
                'attrForm' => 'disabled',
                'sendButtonName' => "Excluir",
                'url' => route('site.delete', $id),
                'method' => 'delete',
                'title' => "Excluir Produto"
            ]
        );
    }

    public function deleteEl($id)
    {
        if($this->repo->delete($id))
            return redirect('/');

        $this->message = $this->repo->getError();
        $this->messageClass = "danger";
        return $this->delete($id);
    }
}

resources/views/edit_product.blade.php
@extends('layouts.site')

@section('title')
   {{$title}}
@endsection


@section('content')
    @if(count($product) == 0)
        <div class="row">
            <h3 class="col-md-offset-3 col-md-6 alert alert-warning">Produto n&atilde;o encontrado.</h3>
        </div>
    @else
        @if(strlen($message) > 0)
            <div class="row">
                <h3 class="col-md-offset-3 col-md-6 alert alert-{{$messageClass}}">{{$message}}</h3>
            </div>
        @endif
        {{Form::open(['url'=>$url, 'method'=>$method])}}
        <div class="form-group">
            <label for="product_external_id">ID</label>
            <label id="product_external_id"class="form-control">{{$product->product_external_id}}</label>   
        </div>
        <div class="form-group">
            <label for="name">Nome</label>
            {{Form::input("text", "name", $product->name, 
            ['class'=>'form-control', "id"=>"name", $attrForm])}}
        </div>

        <div class="form-group">
            <label for="category">Categoria</label>
            {{Form::input("text", "category",$product->category->name, ['class'=>'form-control ', $attrForm, "id"=>"category"])}}
        </div>

        <div class="form-group">
            <label for="description">Descri&ccedil;&atilde;o</label>
            {{Form::textarea("description", $product->description, ['class'=>'form-control', $attrForm, "size"=>"20x5", "id"=>"description"])}}
        </div>

        <div class="form-group">
            <label for="price">Pre&ccedil;o</label>
            {{Form::input("text", "price", number_format($product->price,2), ['class'=>'form-control', $attrForm, "id"=>"price"])}}
        </div>


        <div class="form-group">
            <label for="free_shipping">Entrega Gratu&iacute;ta</label>

            <label>Sim</label>
            <input type="radio" name="free_shipping" value="1" {{$product->free_shipping == 1 ? 'checked' : ''}}>
            <label>N&atilde;o</label>
            <input type="radio" name="free_shipping" value="0" {{$product->free_shipping == 0 ? 'checked' : ''}}>
        </div>
        <hr/>
        {{Form::submit($sendButtonName, ["class"=> "btn btn-success"])}}
        {{Form::close()}}
    @endif
@endsection

resources/views/home.blade.php
@extends('layouts.site')

@section('title')
   Inicio
@endsection


@section('content')
    @if(count($products) == 0)
        <div class="row">
            <h3 class="col-md-offset-3 col-md-6 alert alert-warning">Nenhum item cadastrado.</h3>
        </div>
    @else
        <div class="row">
            <table class="table striped-table">
                <thead>
                    <th>ID</th>
                    <th>Categoria</th>
                    <th>Nome</th>
                    <th>Descri&ccedil;&atilde;o</th>
                    <th class="text-center">pre&ccedil;o</th>
                    <th class="text-center">Frete gratu&iacute;to</th>
                    <th class="text-center">Editar</th>
                    <th class="text-center">Apagar</th>
                </thead>
                <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td>{{$product->product_external_id}}</td>
                            <td>{{$product->category->name}}</td>
                            <td>{{$product->name}}</td>
                            <td>{{$product->description}}</td>
                            <td class="text-center">{{number_format($product->price,2)}}</td>
                            <td class="text-center">{{$product->free_shipping == 1 ? "Sim" : "N&atilde;o"}}</td>
                            <td class="text-center"> 
                                <a class="btn btn-default" 
                                   href="{{route('site.edit',$product->id)}}"
                                >Editar</a>
                            </td>
                            <td class="text-center"> 
                                <a class="btn btn-default" 
                                   href="{{route('site.delete',$product->id)}}"
                                >Apagar</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endif
@endsection

resources/views/importar_sucesso.blade.php
@extends('layouts.site')

@section('title')
   Upload de arquivo
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="btn-success">
                Importado arquivo com sucesso
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/site.blade.php
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title> Teste de programa&ccedil;&atilde;o - @yield('title')</title>
        <meta charset="utf-8">
        <meta name="keywords" content="teste, programacao, leroy-merlin">
        <meta name="description" content="Teste realizado para dev php">
        <meta name="author" content="Evandro Ishy Medeiros">
        <link href="{!! asset('assets/css/bootstrap.min.css') !!}" media="all" rel="stylesheet" type="text/css" />
        <link href="{!! asset('assets/css/style.css') !!}" media="all" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div class="container main">
            <header class="row header">
                <div class="col-md-12 text-center">
                    <h3>Teste Import Xls</h3>
                    <h4>@yield('title')</h4>
                </div>
            </header>
            <nav class="row nav">       
                <a class="col-md-6 col-sm-12 col-xs-12 text-center" href="{!! route('site.index') !!}"><b>Inicio</b></a>
                <a class="col-md-6 col-sm-12 col-xs-12 text-center" href="{!! route('site.upload') !!}"><b>Importar</b></a>
            </nav>
            <main class="container main-container">
                @yield('content')
            </main>
        </div>
        <script src="{!! asset('assets/js/jquery.min.js') !!}"></script>
        <script src="{!! asset('assets/js/jquery-mask.js') !!}"></script>
        <script src="{!! asset('assets/js/product.js') !!}"></script>
        <script src="{!! asset('assets/js/bootstrap.min.js') !!}"></script>
    </body>
</html>

resources/views/upload.blade.php
@extends('layouts.site')

@section('title')
   Upload de arquivo
@endsection


@section('content')
    <div class="row">
    @if(strlen($message) > 0)
        <div class="row">
            <h3 class="col-md-offset-3 col-md-6 alert alert-{{$messageClass}}">{{$message}}</h3>
        </div>
    @endif
            {!! Form::open([
                'url' => route('site.upload'), 
                'type'=> 'POST', 
                'files' => true
            ]) !!}

                <div class="form-group">
                    <input type="file" name="file">
                </div>
                {!!Form::submit("Enviar", ['class' => 'btn btn-info']) !!}
            {!! Form::close() !!}
    </div>
@endsection